import type { Metadata } from "next";

import { inter } from "@/fonts";
import Header from "@/components/header"
import "./global.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='m-0 p-0'>
      <body className={`${inter.className} box-border`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
